### ISSUE TITLE
Option to specify font family for code

### ISSUE THREAD

**Issue by geoah** [infitio/flutter_markdown#2]
Code blocks don't seem to be correctly rendered on MacOS and IOS.
I assume the reason is the same as this https://github.com/flutter/flutter/issues/19280 as from what I can tell flutter_markdown also tries to set the font family to `monospace`.

Would it be possible to have a way to specify the style for code blocks?

**Comment by tiholic** [comment]
@geoah Can you raise a PR with necessary changes

**Comment by geoah** [comment]
@tiholic seems like there is an easy workaround, sorry I didn't really think about this before.

Thank you for this amazing library.

```
        tokenConfigs: [
          MarkdownTokenConfig.code(
            textStyle: textTheme.bodyText1.copyWith(
              fontFamilyFallback: ["Courier"],
            ),
          ),
        ],
```
